export const cursadas = [
    {
        semester: 1,
        subjects: [
            {
                initials: "IAL102",
                title: "Algoritmos e Lógica de Programação",
                status: "Aprovado",
                nf: 9,
                day: "Segunda",
                startTime: "07:40",
                endTime: "11:10",
                teacher: "Chiara",
                qtAulas: 4,
                goals: "Iniciar a formação em programação de computadores por meio de uma linguagem facilitadora do aprendizado de algoritmos, preferencialmente alguma uma linguagem de amplo emprego no mercado",
                summary:  "Conceitos básicos sobre algoritmos e métodos para sua construção. Tipos de dados e variáveis. Álgebra booleana. Estruturas fundamentais de programas: sequencial, condicional e com repetição. Funções. Variáveis compostas homogêneas: vetores e matrizes.",

            },
             {
                initials: "ING007",
                title: "Inglês I",
                status: "Dispensado",
                nf: 9,
                day: "Segunda",
                startTime: "11:20",
                endTime: "13:00",
                qtAulas: 2,
                goals: "Apresentar os recursos da Língua inglesa objetivando desenvolver as quatro habilidades, reading, listening, writing e speaking. Apoiar as atividades de construção de blogs e sítios Internet previstas para o semestre.",
                summary: "Introdução à compreensão e produção oral e escrita por meio da integração das habilidades linguístico-comunicativas. Ênfase na oralidade, atendendo às especificidades acadêmico-profissionais da área e abordando aspectos socioculturais da língua inglesa.",
            },
             {
                initials: "ISW002",
                title: "Bases da Internet",
                status: "Aprovado",
                nf: 9.1,
                day: "Quinta",
                startTime: "11:20",
                endTime: "13:00",
                teacher: "Gerson",
                qtAulas: 2,
                goals: "Fornecer aos estudantes os conhecimentos básicos sobre a Internet. Quem e como a utiliza. Abordar tópicos para permitir aos estudantes desenvolverem habilidades básicas: email, blogs, navegadores, pesquisa, feeds, FTP, downloads, rich media e social media. Explorar vários métodos de comunicação na Web.",
                summary: "Introdução a Internet. Organizações que viabilizam a Internet e a web. Busca de informações. Email, Listas de Email, e Comunicação. Rich Media. Introdução a Redes de computadores. Métodos de compartilhamento de informações. Segurança. Considerações éticas e legais com uso da Internet."
            },
            {
                initials: "ISW003",
                title: "Criação de Conteúdo na Web",
                status: "Aprovado",
                nf: 8.4,
                day: "Quarta",
                startTime: "09:30",
                endTime: "11:10",
                teacher: "Rosemeire",
                qtAulas: 2,
                goals: "Criar conteúdos textuais para páginas da Internet.",
                summary: "Teoria. Adequação comunicativa em diferentes situações de interação. Planejamento de produção de conteúdo textual. Escrita e edição de conteúdo para Web"
            },
            {
                initials: "ISW004",
                title: "Design Digital",
                status: "Aprovado",
                nf: 7.7,
                day: "Sexta",
                startTime: "07:40",
                endTime: "11:10",
                teacher: "Luiz Alexandre",
                qtAulas: 4,
                goals: "Projetar mock-ups (cenas) usando o software de design digital, em seguida implementar o projeto como um sítio Internet.",
                summary: "Apresentar as bases do design gráfico de produção de sítios Internet com emprego de softwares."
            },
             {
                initials: "ISW005",
                title: "Padrões de Projeto de Sítios Internet I",
                status: "Aprovado",
                nf: 7.7,
                day: "Terça",
                startTime: "09:30",
                endTime: "13:00",
                teacher: "Sobrino",
                qtAulas: 4,
                goals: "Apresentar os fundamentos do HTML (Hypertext Markup Language) com ênfase na semântica do uso dos elementos e nos benefícios do emprego de padrões de codificação. Demonstrar uso do CSS (Cascading Style Sheets) para separar conteúdo e apresentação, de modo a aumentar velocidade do desenvolvimento e as habilidades de design",
                summary: "Padrões de projeto para Web. Sintaxe do HTML. Elementos básicos dos conceitos de Web Design. HTML doctypes. Validação do HTML. Boas práticas com HTML e CSS: O CSS, seletores e propriedades. Formulários e estrutura de sítios Internet."
            },
            {
                initials: "LPO004",
                title: "Leitura e Produção de Textos",
                status: "Aprovado",
                nf: 8.4,
                day: "Quinta",
                startTime: "07:40",
                endTime: "11:10",
                teacher: "Vanina",
                qtAulas: 4,
                goals: "Ampliar o domínio da comunicação escrita e oral, por meio da aprendizagem e produção de textos existentes no âmbito acadêmico e tecnológico. Favorecer a interpretação de textos relativos à área do curso",
                summary: "A comunicação na atualidade. Coesão e coerência textuais. Uso e adequação da linguagem. Estratégias de leitura de texto. Produção de texto: resumo acadêmico, resenha crítica, relatório, artigo científico."
            },
            {
                initials: "MAT003",
                title: "Fundamentos da Matemática Elementar",
                status: "Aprovado",
                nf: 9.5,
                day: "Sexta",
                startTime: "11:20",
                endTime: "13:00",
                teacher: "Lourval",
                qtAulas: 2,
                goals: "Discutir os conceitos básicos de matemática",
                summary: "Conjuntos Numéricos. Regras de Três. Frações. Porcentagem. Potenciação e Notação Científica. Radiciação. Logaritmos. Polinômios. Fatoração e Produtos Notáveis. Matrizes. Equações e inequações do 1o. e 2o. Graus"
            },
        ],
    },
    {
        semester: 2,
        subjects: [
            {
                initials: "DDI004",
                title: "Legislação Aplicada à Internet",
                status: "Aprovado",
                nf: 7,
                day: "Segunda",
                startTime: "11:20",
                endTime: "13:00",
                teacher: "Paulo Ferraz",
                qtAulas: 2,
                goals: "Discutir os fundamentos do Direito aplicado à Internet.",
                summary: "Introdução ao Direito. Estudo dos impactos na sociedade trazidos pelo computador. Estudo dos princípios éticos relacionados ao uso da Internet. Noções de perícia forense computacional. Aspectos legais de contrato de serviços de TI. Aspectos legais relacionados à Internet. Garantias legais de acesso à informação (dados abertos). Governos eletrônicos. Aspectos legais quanto a negócios intermediados pela Internet e web."
            },
           {
                initials: "ING008",
                title: "Inglês II",
                status: "Dispensado",
                nf: 9,
                day: "Sexta",
                startTime: "07:40",
                endTime: "09:20",
                qtAulas: 2,
                goals: "Apresentar os recursos do idioma necessários à compreensão e produção oral e escrita por meio da integração das habilidades linguístico-comunicativas. Apoiar as atividades de construção de blogs e sítios Internet previstas para o semestre",
                summary: "Consolidação da compreensão e produção oral e escrita por meio da integração das habilidades linguístico-comunicativas desenvolvidas na disciplina Inglês I. Ênfase na oralidade, atendendo às especificidades acadêmico-profissionais da área e abordando aspectos socioculturais da língua inglesa"
            },
             {
                initials: "IED001",
                title: "Estrutura de Dados",
                status: "Aprovado",
                nf: 7.6,
                day: "Terça",
                startTime: "09:30",
                endTime: "13:00",
                teacher: "Chiara",
                qtAulas: 4,
                goals: "Aprofundar conhecimentos sobre criação e manipulação de tipos abstratos de dados: listas, pilhas, filas e árvores.",
                summary: "Revisão dos conceitos básicos de tipos abstratos de dados. Pilhas, filas, alocação dinâmica, recursividade, listas encadeadas, tabelas de espalhamento e árvores. Aplicações das estruturas de dados em problemas computacionais."
            },
           {
                initials: "ISW006",
                title: "Padrões de Projeto de Sítios Internet II",
                status: "Aprovado",
                nf: 8.7,
                day: "Quarta",
                startTime: "09:30",
                endTime: "13:00",
                teacher: "Sobrino",
                qtAulas: 4,
                goals: "Aprendizado das técnicas avançadas de HTML e CSS para criação de páginas Web de layout sofisticado em conformidade com as diretrizes do W3C. Utilização de microformatos para criar conteúdo semântico e portável. Fornecer ao estudante uma base para criação de sítios acessíveis com aplicação de conceitos do Design Universal para acomodar pessoas com deficiência visual, auditiva, fala, controle motor e distúrbios cognitivos.",
                summary: "Revisão dos padrões de projeto para Web. Tópicos CSS. Esquemas de posicionamento. Elementos flutuantes. Formulários HTML. Elementos de HTML avançado. Técnicas avançadas de reposição de imagem. Seletores avançados do CSS. Microformatos. Técnicas de mosaico de imagens. Resolução de Problemas de layout com uso de depuradores apropriados. Design responsivo. Web semântica. Acessibilidade. Internacionalização."
            },
           {
                initials: "ISW007",
                title: "Prática de Design",
                status: "Aprovado",
                nf: 6.2,
                day: "Segunda",
                startTime: "07:40",
                endTime: "11:10",
                teacher: "Luiz Alexandre",
                qtAulas: 4,
                goals: "Apresentar os tratamentos refinados de imagens e animações com emprego de softwares ou do canvas do HTML5. Ênfase na concepção de uso de várias interfaces interativas compatíveis com interoperabilidade de navegadores com objetivo de analisar usabilidade e acessibilidade.",
                summary: "Tratamento de imagem para composição de cenas para uso na internet. Aplicações de efeitos digitais. Desenvolvimento de layouts interativos para web. Design, interatividade e ambiente. Design, interatividade e ambiente. Introdução à engenharia de usabilidade."
            },
           {
                initials: "IRC009",
                title: "Redes e Internet",
                status: "Aprovado",
                nf: 9.7,
                day: "Quinta",
                startTime: "09:30",
                endTime: "13:00",
                teacher: "Claudio",
                qtAulas: 4,
                goals: "Apresentar detalhadamente as tecnologias de redes de interesse da Internet. Discutir otimização da comunicação e transmissão de dados nos sítios da Internet.",
                summary: "Internet e os protocolos - detalhamento e implementação dos principais protocolos Internet (DNS, HTTP, SMTP, POP3, NNTP e HTTPS). Identificação de problemas (troubleshooting). Métricas Internet para avaliação e otimização de desempenho de tráfego em redes de computadores. Computação em nuvem."
            },
           {
                initials: "MMD003",
                title: "Matemática Discreta",
                status: "Aprovado",
                nf: 9.2,
                day: "Sexta",
                startTime: "09:30",
                endTime: "13:00",
                teacher: "Luciana",
                qtAulas: 4,
                goals: "Apresentar os fundamentos da matemática aplicada ao contexto do curso.",
                summary: " Lógica formal. Teoria dos conjuntos. Matrizes. Determinantes. Sistemas Lineares. Relações. Funções. Análise Combinatória"
            },
        ]
    },
    {
        semester: 3,
        subjects: [
             {
                initials: "IBD005",
                title: "Banco de Dados e Internet I",
                status: "Aprovado",
                nf: 8.5,
                day: "Quinta",
                startTime: "09:30",
                endTime: "13:00",
                teacher: "Anesio",
                qtAulas: 4,
                goals: "Apresentar os conceitos fundamentais sobre banco de dados e modelagem de dados.",
                summary: "Conceitos de bases de dados, modelos conceituais e lógicos de dados. Modelo entidaderelacionamento. Modelo de dados relacional. Teoria relacional. Restrições de integridade. Linguagem SQL (Structured Query Language). Projeto de banco de dados no modelo relacional. Normalização."
            },
             {
                initials: "ING008",
                title: "Inglês III",
                status: "Dispensado",
                nf: 9,
                day: "Quinta",
                startTime: "07:40",
                endTime: "09:20",
                qtAulas: 2,
                goals: "Apresentar os recursos do idioma necessários à compreensão e produção oral e escrita por meio da integração das habilidades linguístico-comunicativas. Apoiar as atividades de construção de blogs e sítios Internet previstas para o semestre.",
                summary: "Expansão da compreensão e produção oral e escrita por meio de funções sociais e estruturas básicas da língua. Ênfase na oralidade, atendendo às especificidades acadêmicoprofissionais da área e abordando aspectos socioculturais da língua inglesa."
            },
             {
                initials: "IED001",
                title: "Engenharia de Software para WEB",
                status: "Aprovado",
                nf: 8.5,
                day: "Terça",
                startTime: "09:30",
                endTime: "13:00",
                teacher: "Rui",
                qtAulas: 4,
                goals: "Apresentar uma visão ampla e contemporânea da Engenharia de software com ênfase nas metodologias aplicadas ao desenvolvimento para Web",
                summary: "Visão Geral da Engenharia de Software – papel evolutivo, paradigmas, ciclo de desenvolvimento. O processo de desenvolvimento: características e processo de desenvolvimento para aplicações Web. Linguagens gráficas para representação dos modelos. Metodologias ágeis. Mapeamento para implementação. Integração do sistema. Testes: planejamento e tipos. Manutenção. Documentação.",

            },
             {
                initials: "ISW008",
                title: "Programação de Sítios para Internet",
                status: "Aprovado",
                nf: 6.6,
                day: "Sexta",
                startTime: "09:30",
                endTime: "13:00",
                teacher: "Alexandre Garcia",
                qtAulas: 4,
                goals: "Apresentar aos estudantes conceitos de programação por meio de ECMAScript (European Computer Manufacturers Association - ECMA) – JavaScript - e Document Object Model (DOM) scripts. Apresentar a história ECMAScript, e seu papel em sítios Internet contemporâneos e aplicações Web. Descrever como Scripts básicos e intermediários são criados para resolver problemas comuns de interface. Aprender a avaliar as bibliotecas existentes e scripts para que possam tomar decisões sobre sua aplicabilidade em uma dada tarefa. Aprender as melhores práticas, técnicas de DOM Scripting (JavaScript).",
                summary: " História do JavaScript. Características do ECMAScript. Melhores práticas de DOM Scripting. Ambientes de testes de JavaScript. ECMAScript: Estrutura léxica, tipos de dados, variáveis de script, expressões e operadores, estruturas de controle, strings e funções de manipulação de strings, objetos e arrays, funções, expressões regulares, objetos Date, Math e Number. Conceitos de programação. DOM Scripting, lado cliente. O modelo de objetos para documentos. Suporte para DOM. Acesso aos elementos do DOM. Classes DOM e sistema de manuseio de bibliotecas e eventos. Eventos temporizados. Manuseio de formulários (validação). Introdução ao AJAX. Propriedades e métodos do objeto Window. Acessibilidade e dispositivos móveis. Erros comuns em DHTML e segurança básica"
            },
             {
                initials: "ISW009",
                title: "Acessibilidade",
                status: "Aprovado",
                nf: 7.3,
                day: "Terça",
                startTime: "07:40",
                endTime: "09:20",
                teacher: "Rosemeire",
                qtAulas: 2,
                goals: "Aplicar técnicas de codificação em HTML e CSS. Avaliar acessibilidade relacionada a softwares de uso comum, scripts, dispositivos móveis e legendagem de Rich media",
                summary: "Design universal. Usabilidade. Acessibilidade. Tecnologia assistiva. Acessibilidade no HTML e CSS. Testes de acessibilidade. Adobe PDF acessível. Dispositivos de multimídia acessíveis. Scripting acessível. Acessibilidade e dispositivos móveis"
            },
             {
                initials: "ISO004",
                title: "Servidores e Seus Sistemas Operacionais",
                status: "Aprovado",
                nf: 9.5,
                day: "Segunda",
                startTime: "09:30",
                endTime: "13:00",
                teacher: "Dora",
                qtAulas: 4,
                goals: "Apresentar os recursos tecnológicos empregados em servidores de redes de computadores.",
                summary: "Identificação dos componentes para montar um servidor, compatibilidade, detalhes sobre as especificações de cada componente, identificação e correção de problemas. Instalação e configuração de softwares (aplicativos gerais, gerenciadores de bancos de dados e sistemas operacionais). Compreender os conceitos, mecanismos e funcionamento dos Sistemas operacionais modernos. Criação de partições, formatação de discos, instalação de drivers. Virtualização de servidores para a implementação de serviços de gerenciamento de usuários, serviços de comunicação e de armazenamento de dados através da utilização de uma intranet composta por aplicativos da internet. Configuração de aplicações e serviços Web. Migração de Web sites e aplicações. Configuração de sites seguros (Controle de acesso e Autenticação)."
            },
             {
                initials: "MET002",
                title: "Estatística",
                status: "Aprovado",
                nf: 9.5,
                day: "Quarta",
                startTime: "09:30",
                endTime: "13:00",
                teacher: "Walter",
                qtAulas: 4,
                goals: "Apresentar Estatística e como utilizá-la para modelar problemas.",
                summary: "Conceitos estatísticos. Gráficos e tabelas. Distribuição de frequência. Medidas de posição. Medidas de dispersão. Medidas separatrizes. Medidas de assimetria e curtose. Diagrama de dispersão e correlação. Regressão Linear Simples. Coeficiente de correlação. Probabilidade. Distribuições de probabilidade: variável aleatória discreta e contínua."
            },
        ],
    },

    {
        semester: 4,
        subjects: [
            {
                initials: "AGO011",
                title: "Prática de Gestão de Projetos",
                status: "Aprovado",
                nf: 7.2,
                day: "Quarta e sexta",
                startTime: "07:40",
                endTime: "09:20",
                teacher: "Renato",
                qtAulas: 4,
                goals: "Conhecer e aplicar técnicas, métodos e ferramentas para uma gestão eficaz de projetos nas suas diferentes facetas, incluindo a equipe de gestão e interações com o cliente. Discutir gestão de equipes multidisciplinares em design e produção de sítios Internet.",
                summary: "Definição de projeto segundo concepção difundida pelas melhores práticas de gestão de projetos. Histórico do desenvolvimento do conjunto de conhecimentos de gestão de projetos. O ciclo de vida de um projeto (concepção, programação, execução, controle e encerramento). Os fatores de sucesso e insucesso de projetos e sua mensuração. Componentes da gestão de projetos: projeto, clientes e equipe. Plano de qualidade. Gestão de integração, escopo, tempo, custos, riscos, recursos humanos, comunicação e qualidade de projetos."
            },
            {
                initials: "ING010",
                title: "Inglês IV",
                status: "Dispensado",
                nf: 9,
                day: "Sexta",
                startTime: "11:20",
                endTime: "13:00",
                qtAulas: 2,
                goals: "Apresentar os recursos do idioma necessários à compreensão e produção oral e escrita por meio da integração das habilidades linguístico-comunicativas. Apoiar as atividades do semestre, inclusive na elaboração dos artigos técnicos.",
                summary: "Aprofundamento da compreensão e produção oral e escrita por meio da integração das habilidades linguístico-comunicativas. Ênfase na oralidade, atendendo às especificidades acadêmico-profissionais da área e abordando aspectos socioculturais da língua inglesa."
            },
            {
                initials: "IBD006",
                title: "Banco de Dados e Internet II",
                status: "Aprovado",
                nf: 8.7,
                day: "Quarta",
                startTime: "09:30",
                endTime: "13:00",
                teacher: "Anesio",
                qtAulas: 4,
                goals: "Apresentar recursos avançados para criação de aplicativos com Banco de dados",
                summary: "Tipos de Junções (join). Subconsultas (Subqueries). Criação, implementação e utilização de procedimentos armazenados (stored procedures), gatilhos (triggers), funções, cursores, visões (view). Linguagem de Controle de Dados. Transações. Bancos de dados orientados a objetos. Bancos de dados multimídia."
            },
            {
                initials: "ISW010",
                title: "Projeto de Navegação e Interação",
                status: "Aprovado",
                nf: 8.7,
                day: "Quinta",
                startTime: "09:30",
                endTime: "13:00",
                teacher: "Rosemeire",
                qtAulas: 4,
                goals: "Apresentar aos estudantes os princípios fundamentais e metodologias de Arquitetura da Informação e do Design da interação com usuário para definir um projeto de software para Internet em termos de sua finalidade, escopo, audiência, elementos principais, fluxos de tarefas, layout, etc. Padrões de projeto. Frameworks serão introduzidos a fim de criar interfaces que mapeiem as expectativas dos usuários e melhorem a experiência do usuário (UX), incluindo levantamentos de requisitos com usuários, avaliação de conteúdo e de organização, documentação de processos no âmbito dos sistemas, definição de estruturas organizacionais e desenvolvimento de protótipos interativos.",
                summary: "Arquitetura de Informação. Levantamento de requisitos / conteúdo Web. Definição do projeto: organização e estrutura de interação. Estrutura de processo. Design de interação. O princípio do projeto da UX. Definição do produto e público. Pesquisa de usuário. Personas. Métodos de investigação e avaliação. Projeto conceitual. Design detalhado. Design da experiência do usuário e otimização de site de busca. Transição da definição para a projeção. Mapas do site e fluxos de tarefa. Prototipagem light. Wireframes e anotações. Teste do design com usuários. Transição do design ao desenvolvimento"
            },
           {
                initials: "IDS001",
                title: "Desenvolvimento para Servidores I",
                status: "Aprovado",
                nf: 6.2,
                day: "Alexandre Garcia",
                startTime: "09:30",
                endTime: "13:00",
                teacher: "Alexandre Garcia",
                qtAulas: 4,
                goals: "Esta disciplina fornecerá uma visão geral da linguagem script PHP associado a um gerenciador de banco de dados que utilize a linguagem SQL e como usar essas tecnologias para gerar sites dinâmicos. Introduzir práticas de codificação seguras",
                summary: "PHP histórico e emprego. Instalação e configuração básica do PHP e um IDE. Sintaxe básica do PHP. Usando o PHP como um mecanismo de modelo simples. Panorama das melhores práticas com PHP. Conceitos de programação HTTP. Codificação de caracteres. Localidades, fusos horários e funções de tempo. Strings. Uso de Array e funções de matriz. Orientação a objetos em PHP (Classes, objetos, herança, encapsulamento, polimorfismo, agregação, composição e métodos). Tratamento de exceções de erro. Arquitetura do lado do servidor. Manipulação de dados postados. Enviando e-mail. Sessões e autenticação. Cookies. Arquivo manuseio e armazenamento de dados em arquivos de texto. Gerenciador de banco de dados e suas funções. Frameworks. Web Services, API, RSS, JSON e Ajax. Hospedagem compartilhada."
            },
           {
                initials: "ISG018",
                title: "Segurança em Sistemas para Internet",
                status: "Aprovado",
                nf: 8.3,
                day: "Terça",
                startTime: "09:30",
                endTime: "13:00",
                teacher: "Claudio",
                qtAulas: 4,
                goals: "Apresentar e discutir as questões relativas à segurança da informação.",
                summary: "Conceitos básicos de segurança da informação. Criptografia, conceitos e uso. Segurança da infraestrutura e das aplicações. Tópicos em desenvolvimento de aplicações seguras. Aspectos legais: validade do documento eletrônico, assinaturas digitais, datação e Infraestrutura de Chave Pública. Aspectos gerenciais: metodologias práticas e normativas referentes às boas práticas de segurança da informação em sistemas diversos, norma ISO/IEC 17799 (família 27.000). Preparação para a implementação, manutenção, monitoramento e melhoria da segurança da informação consistente com a cultura organizacional. Requisitos de segurança da informação: análise; avaliação e gestão de riscos."
            },
             {
                initials: "ITE003",
                title: "Tópicos Especiais em Sistemas para Internet",
                status: "Aprovado",
                nf: 8.4,
                day: "Segunda",
                startTime: "07:40",
                endTime: "09:20",
                teacher: "Mauricio",
                qtAulas: 2,
                goals: "Apresentar tecnologias ainda não estudadas ou aprofundar algum tema já visto definido pela coordenadoria do curso em cada unidade",
                summary: "Recursos e aplicações da tecnologia escolhida."
            },
        ],
    },

    
]